[package]
name = "d8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2"
path = "src/bin/p2.rs"

[[bin]]
name = "p1"
path = "src/main.rs"
